import typescript from '@rollup/plugin-typescript';
import {nodeResolve} from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import { copyFileSync, mkdirSync } from 'fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

const copyManifest = {
  name: 'copy-manifest',
  writeBundle() {
    mkdirSync('dist', { recursive: true });
    copyFileSync('manifest.json', 'dist/manifest.json');
  }
};

export default {
  input: 'main.ts',
  output: {
    dir: 'dist',
    sourcemap: 'inline',
    format: 'cjs',
    exports: 'default',
    banner,
  },
  external: ['obsidian'],
  plugins: [
    typescript({ outDir: 'dist' }),
    nodeResolve({browser: true}),
    commonjs(),
    copyManifest,
  ]
};
